# Generated by Django 3.1.5 on 2021-01-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='use',
            new_name='user',
        ),
    ]
